### ISSUE TITLE
Activating AceJump removes vertical indent guides. 

### ISSUE THREAD

**Issue by Freddster** [acejump/AceJump#205] opened 2017-12-01 09:03 UTC
**Problem:** When AceJump either executes or terminates the vertical indent lines disappears, as though they are disabled. This happens when using all of the AceJump shortcuts. The problem arises when both executing a "jump" with AceJump, and even if AceJump is cancelled with Esc. 

One way to get the indent guides back is to deactivate them with a hotkey, and then activate them again. Another way which is to simply close the file, and reopen it, then the lines appear again. Because of this last method, I conclude that the lines them selves have not been deactivated by AceJump, but rather been hidden in some sort of fashion.

I normally use the Material Theme UI, but this behavior also appears when I disable the Material Theme UI, and use the standard Darcula theme.

**Screenshot**
Before image: 
![image](https://user-images.githubusercontent.com/17593039/33473442-c3c6e252-d676-11e7-8a89-7808a2e26d93.png)

After cancelling AceJump with Esc:
![image](https://user-images.githubusercontent.com/17593039/33473611-7241ff92-d677-11e7-87d6-d618d32fdb85.png)

System:
IntelliJ IDEA 2017.2.5
Build #IC-172.4343.14, built on September 26, 2017
JRE: 1.8.0_152-release-915-b12 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 8.1 6.3

List of plugins:
AceJump 3.4.2
Android Support 10.2.3
Ant Support 1.0
Build JSON 1.2.1
Bytecode Viewer 0.1
Copyright 8.1
Coverage 172.4343.14
CVS Integration 11
Eclipse Integration 3.0
EditorConfig 172.4343.14
Force Shortcuts 0.4
Git Integration 8.1
GitHub 172.4343.14
Gradle 172.4343.14
Goovy 9.0
hg4idea 10.0
l18 for Java 172.4343.14
IntelliLang 8.0
Java Bytecode Decompiler 172.4343.14
JavaFX 1.0
JUnit 1.0
Kotlin 1.1.4
Lombok Plugin 0.15.17.2
Material Theme UI 1.3.7
Maven Integration 172.4343.14
Plugin DevKit 1.0
Properties Support 172.4343.14
Scroll From Source 1.1.3
Settings Repository 172.4343.14
Subversion Integration 1.1
Task Management 1.0
Terminal 0.1
TestNG-J 8.0
UI Designer 172.4343.14
XPathView + XSLT Support 4
XSLT-Debugger 1.4
YAML 172.4343.14

**Comment by Freddster** [comment] 2017-12-01 14:38
Note: Just updated to IntelliJ 2017.3 and the problem still occurs:

IntelliJ IDEA 2017.3 (Community Edition)
Build #IC-173.3727.127, built on November 27, 2017
JRE: 1.8.0_152-release-1024-b6 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 8.1 6.3

**Comment by saroff** [comment] 2017-12-20 12:37
Same on

IntelliJ IDEA 2017.3.1 (Ultimate Edition)
Build #IU-173.3942.27, built on December 11, 2017
Licensed to IntelliJ IDEA Evaluator
Expiration date: December 31, 2017
JRE: 1.8.0_152-release-1024-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by breandan** [comment] 2017-12-20 19:58
Thanks for the detailed reports. This is a very strange bug - the only place where we use IntelliJ IDEA's `FoldingModel` is to check if an index [has been folded](https://github.com/johnlindquist/AceJump/blob/61e5b859132dc55df568c474ced0d654599bfc6b/src/main/kotlin/com/johnlindquist/acejump/search/AceUtil.kt#L42). I have no idea what might be causing this to occur, but will investigate.

**Comment by saroff** [comment] 2018-03-05 10:38
Still happening on 
IntelliJ IDEA 2017.3.4 (Ultimate Edition)
Build #IU-173.4548.28, built on January 30, 2018

JRE: 1.8.0_152-release-1024-b11 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by breandan** [comment] 2018-03-06 02:15
I can reproduce, but I don't have a fix and I'm pretty certain this is a platform issue. If this bug is caused by something we're doing, it probably happens around [here](https://github.com/johnlindquist/AceJump/blob/37c55cb6d61fa904569d30816d395f2d354775c1/src/main/kotlin/com/johnlindquist/acejump/control/Handler.kt#L150) in case anyone wants to investigate.

**Comment by geoelectric** [comment] 2018-03-22 23:54
I'm seeing this on Mac in latest WebStorm as well, though I'm sure it is platform-related. My only other plugin is IdeaVim. For me, the guides restore as soon as the text in the editor changes at all (presumably indents are recalculated when that happens).

**Comment by breandan** [comment] 2021-11-21 08:00
Closing, as this does not appear to be AceJump specific. Please feel free to report on [YouTrack](https://youtrack.jetbrains.com/issues/IJSDK) if this issue persists.

**Closed by breandan** 2021-11-21 08:00 UTC
Labels: bug
