### ISSUE TITLE
Settings are not saved after restarting

### ISSUE THREAD

**Issue by miirinjej** [acejump/AceJump#226] opened 2018-03-28 16:58 UTC
WebStorm 2017.3/2018.1

I set the colors, characters in Tools > AceJump options and after restart IDE, they are reset on default.

**Comment by h0tk3y** [comment] 2018-05-25 01:04
This happens to me as well. I'd really appreciate a fix for this issue.

**Comment by andrewpsy** [comment] 2018-06-28 15:19
Just observed the same behavior in GoLand and Rider from JetBrains.

**Comment by sm4sh** [comment] 2018-07-05 14:53
PhpStorm too

**Comment by breandan** [comment] 2018-10-08 22:30
This should now be fixed in AceJump `3.5.1`. Please update and report any issues you may encounter.

**Comment by fools-mate** [comment] 2020-05-11 06:58
The problem now reappears with current version 3.6.1.
Can anyone confirm this as well?

I' using WebStorm 2020.1.1 under macOs Catalina 10.15.4.

**Comment by qdo-se** [comment] 2020-05-14 20:28
I got the same issue with version 3.6.1. 
I am using IntelliJ IDEA 2020.1 with macOS Catalina 10.15.4.

**Comment by fools-mate** [comment] 2020-05-18 17:28
@breandan Can you take a look at this, please?

**Comment by breandan** [comment] 2020-05-19 05:10
Looked into it, and I can reproduce this issue, but I'm not quite sure why it's happening at the moment. We recently removed the `application-compontents` tag in d70f6939d558da4aafde6f6e50a880aa3f76512e/#322, but that should not have changed the save behavior. I have a hunch that Kotlin `object`s might interfere with way the platform instantiates services:

https://github.com/acejump/AceJump/blob/083c030edb0594789c5dcdb7a3314107d7e2728d/src/main/kotlin/org/acejump/config/AceConfig.kt#L17-L18

But after turning it into a class, the settings still were not persisted following a restart. @AlexPl292 Are you aware of any changes to the way [persistence](https://www.jetbrains.org/intellij/sdk/docs/basics/persisting_state_of_components.html) works in `2020.1+`?

**Comment by AlexPl292** [comment] 2020-05-19 07:43
@breandan hey, I haven't investigated this in-depth, but from the first look:
- `AceConfig` should be a class. Actually, kotlin's objects should not be used as services/components/configurables or any other things that declared in `plugin.xml`.
You can declare `AceConfig` as an application service and get it using `ApplicationManager.getApplication().getService()`.
- I'm 80% sure that `AceConfig` as application service and `AceConfig` as configurable have to be split into two separate classes. `configurable` should save the state into `application service` and `PersistentStateComponent` should be applied to `application service`.
- I don't know about the location where `AceJump.xml` will be saved if you just declare it as `Storage("AceJump.xml")`. Could you try to use `Storage("\$APP_CONFIG$/AceJump.xml")`? In this case, `AceJump.xml` will be saved in IJ configuration folder. (don't forget to escape first `$` otherwise it'll be resolved as a variable).

I'm not aware of any changes in persistence. Maybe you can try to check the things I've described and let be know if it'll fix the problem or not?

**Comment by breandan** [comment] 2020-05-20 05:23
Tried separating the `applicationService` ([`AceConfig`](https://github.com/acejump/AceJump/blob/06b2322b85c9394b1d55c57d4364fd9ac49fb533/src/main/kotlin/org/acejump/config/AceConfig.kt)) from the `applicationConfigurable` ([`AceConfigurable`](https://github.com/acejump/AceJump/blob/06b2322b85c9394b1d55c57d4364fd9ac49fb533/src/main/kotlin/org/acejump/config/AceConfigurable.kt)) and using the platform's dependency injection API to [retrieve the service](https://github.com/acejump/AceJump/blob/06b2322b85c9394b1d55c57d4364fd9ac49fb533/src/main/kotlin/org/acejump/config/AceConfig.kt#L28). Also updated storage path [as suggested](https://github.com/acejump/AceJump/blob/06b2322b85c9394b1d55c57d4364fd9ac49fb533/src/main/kotlin/org/acejump/config/AceConfig.kt#L16), but no luck. Odd, this seemed to work in earlier versions.

Someone should figure out why Kotlin objects do not play well with Picocontainer or add a warning about this in the [SDK docs](https://www.jetbrains.org/intellij/sdk/docs/tutorials/kotlin.html).

**Comment by AlexPl292** [comment] 2020-05-20 07:40
PR created. The root cause was in another one circular dependency between properties, but the changes were still worth it :)

**Closed** 2020-05-20 15:19 UTC
Labels: bug

**Comment by breandan** [comment] 2020-05-20 15:42
Nice, that must have been tricky to debug! I can confirm #330 works. How were you able to identify this issue? Just by reading the code or was there a stack trace somewhere in the log? Usually circular deps blow the call stack, but I guess the platform DI must have prevented it?

Maybe there is a way to detect cyclical dependencies using static analysis or by throwing an exception at test time. Seems like a regression either in the AceJump codebase or in the platform, as this originally worked, but failed silently, maybe during the migration to `2020.1` or in #326?

**Comment by AlexPl292** [comment] 2020-05-21 06:55
At some point of debugging, I realized to check logs (well, I should have started with that) and the problem was logged there (something like `variable `settings` is null but it must be non-null`). I don't think that was a platform regression or DI should prevent it. That seems to be problem with the code only: variable `a` is trying to initialize, but it depends on variable `b`, `b` depends on `c` and `c` depends on `a`. And the plugin fails with NPE because `a` isn't initialized. There are some checks in IJ for java that prevent similar situations (like "do not call an abstract method in the constructor"), but I don't know if they are implemented for Kotlin, or are there any checks for this case.
Seems like this issue isn't discoverable unless this code is called. So, maybe it's just needed to add some tests that cover this class.

**Comment by Emigre** [comment] 2020-05-25 14:12
thanks @AlexPl292. @breandan could we release a patch version of the plugin now that this is fixed? I have the latest (3.6.1) and I see this issue, which is quite annoying. thanks : )
