### ISSUE TITLE
Multiple-editors and split-screen related issues

### ISSUE THREAD

**Issue by rocketraman** [acejump/AceJump#71] opened 2016-07-09 22:15 UTC
AceJump works in a primary group, but not in a secondary group. Repro:

1) Open two files.

2) Right-click on one file's tab, select "Move Right"

3) Move to the new pane on the right.

4) Attempt to use AceJump.

**Comment by breandan** [comment] 2016-07-17 04:03
![screen shot 2016-07-17 at 12 01 29 am](https://cloud.githubusercontent.com/assets/175716/16898684/aa4c4c32-4bb1-11e6-8960-0ea9cf2e56be.png)

Couldn't reproduce this issue. What version and IDE are you using?

**Comment by rocketraman** [comment] 2016-07-19 14:26
I was on 2.0.9 before, but I just tried it with the recently released version 2.0.13 on 2016.2 and it is working fine now! Thanks.

**Comment by rocketraman** [comment] 2016-08-08 17:22
Oddly enough, now the issue is back! Not sure how to reproduce it or why it seems to be a transient problem.

**Comment by rocketraman** [comment] 2016-09-01 13:10
I think I've found a repro. The repro is: make the group on the right smaller.

AceJump will stop displaying the jump letters. It still activates and jumps, but the jump cannot be controlled since the letters are not visible.

This does not affect the group on the left for some reason. Also, I cannot identify the breakpoint between the size where it works and the size where it doesn't.

**Comment by rocketraman** [comment] 2016-12-01 22:32
BTW, this is still reproducible in the latest 3.x version of Acejump, with the exact same behavior. When the right group is small enough, acejump activates but the shortcut letters are invisible (but active).

**Comment by breandan** [comment] 2017-02-27 19:25
I think I see what's happening here. When you make a vertical split *really* small, the tags become invisible, right?

<img width="1280" alt="screen shot 2017-02-27 at 2 20 10 pm" src="https://cloud.githubusercontent.com/assets/175716/23375848/dcf278b2-fcf7-11e6-8ddd-6966d3a312c0.png">

<img width="1280" alt="screen shot 2017-02-27 at 2 23 35 pm" src="https://cloud.githubusercontent.com/assets/175716/23375972/58dd20e4-fcf8-11e6-98a5-640663d3514c.png">

I think this behavior might have something to do with the IntelliJ Platform. Does this problem happen often enough to become a major inconvenience?

**Comment by rocketraman** [comment] 2017-02-27 19:36
Now that I understand why it is happening and how to fix it when it does, no it is not much of an inconvenience at all. However, note on my machine I don't **need** to make it **really** small in order to see this behavior. The right pane is still usable, but jumps invisible. For example, here it is working:

![image](https://cloud.githubusercontent.com/assets/53049/23376393/e60194ea-fcf9-11e6-841e-27215815c078.png)

and partially working:

![image](https://cloud.githubusercontent.com/assets/53049/23376428/060e5a52-fcfa-11e6-92eb-6d558f9fd957.png)

You can see the right pane is still quite usable, so this is not an unusual situation.

**Comment by naclander** [comment] 2020-06-09 20:05
FWIW I'm still seeing this issue in Pycharm CE 2020.1

**Comment by breandan** [comment] 2021-04-04 04:12
This should be fixed in [`3.7.0`](https://plugins.jetbrains.com/plugin/7086-acejump/versions/stable/115735). Please free to give it a try and leave your feedback!

**Closed by breandan** 2021-04-04 04:12 UTC
Labels: bug

**Comment by rocketraman** [comment] 2021-04-05 12:00
> This should be fixed in [`3.7.0`](https://plugins.jetbrains.com/plugin/7086-acejump/versions/stable/115735). Please free to give it a try and leave your feedback!

Confirmed, working well in 3.7.0! Thanks.
