### ISSUE TITLE
AceJump shortcut does nothing after some time.

### ISSUE THREAD

**Issue by konstantin-tarasov-sb** [acejump/AceJump#185] opened 2017-08-22 10:04 UTC
In WebStorm 2017.2.2 after some time of using editor AceJump shortcut stops responding. Nothing happens at all for all AceJump combinations.
I can't find exact steps to reproduce it, but it can be reproduced quite fast by messing with editor split windows. 
I attached video. Looks like steps is creating a lot of split windows -> closing them.

[Acejump bug.zip](https://github.com/johnlindquist/AceJump/files/1241634/Acejump.bug.zip)

**Comment by konstantin-tarasov-sb** [comment] 2017-08-22 10:05
https://github.com/johnlindquist/AceJump/issues/178
Maybe related.

**Comment by jgololicic** [comment] 2017-08-28 12:30
same issue here ...

PhpStorm 2017.2.1
Build #PS-172.3544.41, built on August 2, 2017
Subscription is active until February 16, 2018
JRE: 1.8.0_152-release-915-b6 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.4

**Comment by xc1427** [comment] 2017-08-30 15:55
same issue here...

IntelliJ IDEA 2017.2.2
Build #IU-172.3757.52, built on August 15, 2017
JRE: 1.8.0_152-release-915-b10 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.6

**Comment by breandan** [comment] 2017-08-30 19:09
Thanks for reporting. Will try to reproduce.

**Comment by breandan** [comment] 2019-10-30 00:52
Probably a duplicate of #71 considering the split screen evidence, seems to be a recurring issue. Let's move the discussion over there, thanks for reporting.

**Closed by breandan** 2019-10-30 00:52 UTC
Labels: bug
