### ISSUE TITLE
Jumping to select word doesn't work

### ISSUE THREAD

**Issue by Slapbox** [acejump/AceJump#413] opened 2022-09-08 01:48 UTC
**Describe the bug**
Jumping to select word doesn't work

**To Reproduce**
Double tap the hotkey for word selection, then try to select a word. The cursor remains at its original position. This does not affect non-word-selection mode.

**Expected behavior**
Jumps to newly requested word

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Kubuntu 22.04
 - IDE and version 2022.2.1
 - AceJump version: 3.8.8

**Additional context**

By the way, I just learned about this and it's god damn amazing. Thank you for the great work!

**Comment by breandan** [comment] 2023-02-13 22:01
Unable to reproduce. Were you using the cycle selection method or the hotkey directly assigned to target mode? When activated correctly, you should see a visual indicator around the targeted word that looks as follows:

<img width="346" alt="Screenshot 2023-02-13 at 4 59 33 PM" src="https://user-images.githubusercontent.com/175716/218584240-e89a065a-57b7-4e4d-bb57-601c548f24e5.png">

After selecting the tag, the resulting editor state should appear as follows:

<img width="344" alt="Screenshot 2023-02-13 at 5 00 38 PM" src="https://user-images.githubusercontent.com/175716/218584448-c09574e2-2fb6-4746-9f2c-15cbc42742b0.png">

Feel free to reopen if the issue persists.

**Closed by breandan** 2023-02-13 22:01 UTC
Labels: bug
