### ISSUE TITLE
Searching something in target mode leave the cursor in block mode

### ISSUE THREAD

**Issue by TheBestPessimist** [acejump/AceJump#269] opened 2019-01-11 07:14 UTC
Intellij idea 2018.3.3, windows 10.

Possibly the same issue as in #267?

1. press `ctrl+;` twice to start target mode
2. type whatever you want to move to
3. press the letter combo to go there
4. the text is selected (good)
5. BUG: the caret is now always a block and i have to restart IDE to get it back to line (not even changing it in settings fixes this).

Is there anything i can give you to help debug this?

**Comment by breandan** [comment] 2019-01-11 11:08
Thank you for reporting this issue. This is a duplicate of #267 and should be fixed in the next release.

**Closed** 2019-03-23 02:22 UTC
