### ISSUE TITLE
Constant errors since Rider 2021.2

### ISSUE THREAD

**Issue by peppy** [acejump/AceJump#382] opened 2021-08-10 06:23 UTC
I'm not sure on the exact reproduction case, but it seems like the error log will be enough to track down the issue here.

```csharp
Access is allowed from event dispatch thread only

com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: EventQueue.isDispatchThread()=false Toolkit.getEventQueue()=com.intellij.ide.IdeEventQueue@1f45a792
Current thread: Thread[SE-SearchTask-ActionSearchEverywhereContributor,4,main] 12942193
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,main] 1632580801
	at com.intellij.openapi.application.impl.ApplicationImpl.throwThreadAccessException(ApplicationImpl.java:1030)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:1005)
	at com.jetbrains.rider.actions.InterruptibleBackendActionHost.hasInterruptibleAction(InterruptibleBackendActionHost.kt:46)
	at com.jetbrains.rider.actions.RiderActionEscapeHandler.isEnabledForCaret(RiderActionEscapeHandler.kt:20)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.isEnabled(EditorActionHandler.java:125)
	at com.intellij.xdebugger.impl.actions.handlers.XDebuggerSmartStepIntoHandler$SmartStepEditorActionHandler.isEnabledForCaret(XDebuggerSmartStepIntoHandler.java:423)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.isEnabled(EditorActionHandler.java:125)
	at com.intellij.refactoring.changeSignature.inplace.EscapeHandler.isEnabledForCaret(EscapeHandler.java:51)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.isEnabled(EditorActionHandler.java:125)
	at com.intellij.codeInsight.template.impl.editorActions.EscapeHandler.isEnabledForCaret(EscapeHandler.java:73)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.isEnabled(EditorActionHandler.java:125)
	at org.acejump.action.AceEditorAction.isEnabledForCaret(AceEditorAction.kt:17)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.isEnabled(EditorActionHandler.java:125)
	at com.jetbrains.rdclient.actions.base.FrontendEditorActionHandler.isEnabledForCaret(FrontendEditorActionHandler.kt:41)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.doIfEnabled(EditorActionHandler.java:88)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.isEnabled(EditorActionHandler.java:68)
	at com.intellij.openapi.editor.actionSystem.DynamicEditorActionHandler.isEnabled(DynamicEditorActionHandler.java:45)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.isEnabled(EditorActionHandler.java:125)
	at com.intellij.openapi.editor.actionSystem.EditorAction.update(EditorAction.java:107)
	at com.intellij.openapi.editor.actionSystem.EditorAction.update(EditorAction.java:152)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performDumbAwareUpdate$0(ActionUtil.java:130)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:144)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.doUpdate(ActionUpdater.java:573)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$updateActionReal$7(ActionUpdater.java:129)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.callAction(ActionUpdater.java:172)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.updateActionReal(ActionUpdater.java:130)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$new$0(ActionUpdater.java:110)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.update(ActionUpdater.java:559)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater$UpdateSessionImpl.presentation(ActionUpdater.java:670)
	at com.intellij.ide.util.gotoByName.GotoActionModel$ActionWrapper.lambda$new$0(GotoActionModel.java:645)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.insideReadAction(NonBlockingReadActionImpl.java:521)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$attemptComputation$3(NonBlockingReadActionImpl.java:486)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1078)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:78)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:161)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:118)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:57)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:183)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:57)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:115)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:78)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.attemptComputation(NonBlockingReadActionImpl.java:486)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.executeSynchronously(NonBlockingReadActionImpl.java:421)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl.executeSynchronously(NonBlockingReadActionImpl.java:186)
	at com.intellij.ide.util.gotoByName.GotoActionModel$ActionWrapper.<init>(GotoActionModel.java:647)
	at com.intellij.ide.util.gotoByName.GotoActionItemProvider.lambda$processActions$7(GotoActionItemProvider.java:232)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.DistinctOps$1$2.accept(DistinctOps.java:175)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1603)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312)
	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at com.intellij.ide.util.gotoByName.GotoActionItemProvider.processItems(GotoActionItemProvider.java:279)
	at com.intellij.ide.util.gotoByName.GotoActionItemProvider.processActions(GotoActionItemProvider.java:235)
	at com.intellij.ide.util.gotoByName.GotoActionItemProvider.filterElements(GotoActionItemProvider.java:94)
	at com.intellij.ide.actions.searcheverywhere.ActionSearchEverywhereContributor.fetchWeightedElements(ActionSearchEverywhereContributor.java:99)
	at com.intellij.ide.actions.searcheverywhere.MixedResultsSearcher$ContributorSearchTask.run(MixedResultsSearcher.java:177)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:213)
	at com.intellij.util.ConcurrencyUtil.lambda$underThreadNameRunnable$3(ConcurrencyUtil.java:201)
	at com.intellij.codeWithMe.ClientId$Companion$decorateRunnable$1.run(ClientId.kt:194)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:265)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by sid-6581** [comment] 2021-08-30 03:38
I get these errors constantly as well. Also on 2021.2.1.

**Comment by breandan** [comment] 2021-10-01 05:17
Hmm, it looks like this line is the culprit:

https://github.com/acejump/AceJump/blob/cb10ff77892337b3ede8d8396b9788994383212c/src/main/kotlin/org/acejump/action/AceEditorAction.kt#L17

In the past, we wrapped EDT actions using [`invokeLater`](https://plugins.jetbrains.com/docs/intellij/general-threading-rules.html?from=jetbrains.org#modality-and-invokelater) to deal with these sorts of errors. During the refactor, we tried to eliminate these calls due to threading issues, but I forget what alternative was exactly.

@chylex Any ideas what might be going on here?

**Comment by chylex** [comment] 2021-10-01 05:55
The `isEnabled` calls are simply delegated, so every plugin that has an editor handler will show up in this stack. I'm afraid the stack trace is not helpful and doesn't point to the actual cause, which could be a different plugin or a bug in Rider that is calling `EditorActionHandler` methods outside of UI thread.

FWIW, I don't get any errors in my Rider 2021.2.1, so I suspect if you disable AceJump, you will continue to see the errors.

I'm not sure how you got the Code With Me plugin because it doesn't show up in my Rider at all, but the beginning of the stack points to it: `at com.intellij.codeWithMe.ClientId$Companion$decorateRunnable$1.run(ClientId.kt:194)`. If disabling it doesn't fix it, then you'll have to figure out where the non-UI thread itself is being created.

**Comment by chylex** [comment] 2021-10-01 06:03
It looks like some utilities from the `com.intellij.codeWithMe` package are included in IJ itself and unrelated to the plugin, so the only option is to find what's creating the non-UI thread.

**Comment by peppy** [comment] 2021-10-01 06:07
Thanks, this does look to happen even with AceJump disabled. I do recall trying this and couldn't repro, but may have been a mistake at my end.

I don't have any "code with me" plugins installed, so it seems like this is as mentioned, some included/hidden functionality.

**Comment by peppy** [comment] 2021-10-01 06:47
After disabling all plugins and trying to figure out what was going on by enabling one at a time, I can't seem to reproduce the issue any more. Very weird.

I'm not going to close this thread because it *seems like* there are others in this thread having the same issue and may be able to provide more insight? But feel free to close at your discretion.

**Comment by breandan** [comment] 2021-10-01 06:53
@chylex @peppy Okay, thanks for following up on this one. I guess it's something Rider-specific. CC: @igor-akhmetov

**Comment by breandan** [comment] 2021-12-23 22:37
Although AceJump does appear in @peppy's original stacktrace, I'm going to close this issue as it would not appear to be caused by AceJump directly. If someone believes otherwise and has an update, please feel free to reopen. Thanks!

**Closed by breandan** 2021-12-23 22:37 UTC
Labels: bug
