### ISSUE TITLE
After typing the first char, the "selections list" appears and suddenly disappears

### ISSUE THREAD

**Issue by LukMas** [acejump/AceJump#131] opened 2017-03-14 10:29 UTC
Steps: 
1. activated with ctrl+;
2. type single char
Result: The list of selections appears and suddenly disappears, no way to keep it active.

I'm using the last version of Idea with JDK8 on Ubuntu 14.04.

Thank you for fixing it. 
regards

**Comment by dale19900108** [comment] 2017-03-17 02:06
I have the same issue .
it's suddenly happen .it's work well just before happen 
 last version of Idea with JDK8 on Mac
try to reinstall but not used .

**Comment by dale19900108** [comment] 2017-03-17 02:20
@johnlindquist please fix it。I can't work without this plugin....
If you need any information please contract me AT
18612484680@163.com

**Comment by breandan** [comment] 2017-03-17 02:55
@dale19900108 @LukMas Could you please provide your exact version number for IntelliJ IDEA and JDK8 so that I can try to reproduce this issue? From the main menu, select `IntelliJ IDEA | About IntelliJ IDEA` paste the following information, like so:

> IntelliJ IDEA 2017.1 EAP
> Build #IU-171.3780.15, built on March 8, 2017
> IntelliJ IDEA EAP User
> Expiration date: April 7, 2017
> JRE: 1.8.0_112-release-736-b10 x86_64
> JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
> Mac OS X 10.11.6

Additionally, if you have noticed any error message, attaching that would also help diagnose the issue. Thanks for reporting.

**Comment by dale19900108** [comment] 2017-03-17 03:00
IntelliJ IDEA 2016.3.5
Build #IU-163.13906.18, built on March 6, 2017
Licensed to liuchong

JRE: 1.8.0_112-release-408-b6 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

where can I see the error message ?

**Comment by breandan** [comment] 2017-03-17 03:12
> where can I see the error message ? @breandan

In your log, under `Help | Show log in finder`. (Then attach that file.) Thanks.

**Comment by dale19900108** [comment] 2017-03-17 03:16
[idea.log.zip](https://github.com/johnlindquist/AceJump/files/849562/idea.log.zip)
this is the log  .

**Comment by dale19900108** [comment] 2017-03-17 03:29
I just found another question ,
I must enter thy key twice  to activate  AceJump mode .
and In keyMap setting  the activate key  is just one ,no second stroke .

**Comment by dale19900108** [comment] 2017-03-17 09:57
what  ? It's work agin ....
and .the questions of need twice hit key to activate AceJump mode disappear .
I don't do anything...

**Comment by hotdust** [comment] 2017-04-07 04:51
HI, Yesterday, Acejump worked verywell, today I have same question.

But I found it work again **if you resized idea window to half ( a little bigger or smaller works too) of monitor**. 
I do not know whether this message can help resolve problom.

Spec below:
System: 
OSX EI Capitan 10.11.6

IntelliJ IDEA 2017.1
Build #IU-171.3780.107, built on March 22, 2017
Subscription is active until January 30, 2018
JRE: 1.8.0_112-release-736-b13 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.11.6

**Comment by hotdust** [comment] 2017-04-07 05:30
It works again.
I delete module, and re-download it from git, then it works again.

(PS:before downloading, I rebooted idea and MAC, but it still does not work.
  Maybe this issue connect with idea xml file. 
  I did download source of jar by maven command(mvn dependency:resolve -Dclassifier=sources))

**Comment by hotdust** [comment] 2017-04-10 04:09
sometimes this bug occurs on different files

**Comment by 569258yin** [comment] 2017-04-16 01:44
I meet the same question.
IntelliJ IDEA 2017.1.1
Build #IU-171.4073.35, built on April 7, 2017
Licensed to MyPC

JRE: 1.8.0_112-release-736-b16 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by 569258yin** [comment] 2017-04-16 01:54
I also found a problem that he did not work in a file, working properly in other files, but I did not find any difference between these files

**Comment by MinRam** [comment] 2017-05-06 20:15
I am also facing this problem.
-  "ctrl +;“ active ac
- it  lose immediately the focus after pressing  some character  at somtime;
![image](https://cloud.githubusercontent.com/assets/14797464/25775611/928e4aca-32db-11e7-9cb4-995028550fac.png)
>my system  is window 10

**Comment by breandan** [comment] 2018-12-31 04:55
I think this issue should be fixed on a more recent version (as we have since changed the trigger mechanism somewhat) but please feel free to reopen if this is not the case.

**Closed by breandan** 2018-12-31 04:55 UTC
Labels: bug
