### ISSUE TITLE
cannot put selection into yank in ideavim

### ISSUE THREAD

**Issue by ctrngk** [acejump/AceJump#128] opened 2017-03-09 12:25 UTC
AceJump provides `shift` to select the interval between jump, however, as ideavim user, press `y` for multiple lines of selections  does not work as expected. 
I use `cmd + c`, `cmd + v` to get around this problem for the time being. Simply paste by `p` only contains one line.

**Comment by breandan** [comment] 2017-06-01 11:00
Possibly related: #68.

**Comment by breandan** [comment] 2018-10-13 16:59
This issue is actually caused by #220, and possibly something IdeaVim needs to fix. I'm going ahead and closing this issue as #220 has more details, please follow that thread for updates. @ctrngk @ecbrodie

**Closed by breandan** 2018-10-13 16:59 UTC
Labels: enhancement
