### ISSUE TITLE
Exception after selecting keywords: IndexOutOfBoundsException

### ISSUE THREAD

**Issue by vladshkerin** [acejump/AceJump#334] opened 2020-08-16 18:25 UTC
**Describe the bug**
After entering key characters and pressing enter an **IndexOutOfBoundsException** occurs.

**To Reproduce**
1. Press 'Ctrl + ;'
2. Enter any key characters
3. Click on 'Enter'
4. See exception

**Screenshots**
![Screenshot_20200816_211544](https://user-images.githubusercontent.com/12407716/90341146-c737c280-e005-11ea-91a9-d608136af47d.jpeg)

**Desktop (please complete the following information):**
 - OS: **Kubuntu 20.04**
 - IDE **IntelliJ IDEA 2020.1.4 Build #IU-201.8743.12**
 - Java **OpenJDK 11.0.7+10-b765.65**
 - AceJump **3.6.3**

**Additional context**
[actjump_exception.txt](https://github.com/acejump/AceJump/files/5081196/actjump_exception.txt)

**Comment by breandan** [comment] 2021-04-04 04:21
I was unable to reproduce this issue, but I am reasonably sure issue it was fixed in [`3.7.0`](https://plugins.jetbrains.com/plugin/7086-acejump/versions/stable/115735). Feel free to give it a try and let us know if not.

**Closed by breandan** 2021-04-04 04:21 UTC
Labels: bug
