### ISSUE TITLE
Typescript slow syntax highlighter

### ISSUE THREAD

**Issue by imkarma** [acejump/AceJump#244] opened 2018-07-14 20:52 UTC
When plugin AceJump ON, files with >200 lines of code write on TypeScript start laging and highlighter is very slow

**Comment by breandan** [comment] 2018-10-08 23:09
Duplicate of #207, #217, thank you for reporting. Quick workaround is to type multiple search characters quickly (e.g. if you are trying to jump to a word like `external` in some document, then type `ex` or `ext` instead of just `e` and waiting for tags to appear.)

**Closed by breandan** 2018-10-08 23:09 UTC
