### ISSUE TITLE
Issues running AceJump on multiple IDE windows

### ISSUE THREAD

**Issue by imornar** [acejump/AceJump#177] opened 2017-07-27 11:52 UTC
When I first start Webstorm, lets say project "x" Acejump works as expected.
If I open other project "y" (both for new window or this window) Acejump stops working.
Anyone having similar issue?

**Comment by breandan** [comment] 2017-07-31 15:45
I think it is caused by the way we initialize the plugin, never tested this scenario. Will fix, thanks for reporting.

**Comment by msafi** [comment] 2017-08-08 20:09
I wonder if this is some how related to https://github.com/johnlindquist/AceJump/issues/138

**Comment by Android-s14** [comment] 2017-08-14 14:59
Is there some fix for this bug? I'm not sure if I have the same one but I have to restart intellij every 15 minutes to keep enjoying the plugin. Happens both on 2017.1 and 2017.2, Linux. I cannot attribute it to some specific action, it just happens eventually. 

I can see a few "stopped working" issues and I was wondering if they all point to the same problem.

**Comment by breandan** [comment] 2018-12-31 04:52
The main issue is due to the way we handle state with AceJump. The IDE only creates one instance of each plugin, even if there are multiple windows. When switching between windows, this can cause an inconsistent state to arise. The solution for now is to either use a single editor window, or always make sure to press <kbd>Esc</kbd> when switching between projects so AceJump's state is reset.

**Comment by breandan** [comment] 2019-10-30 00:49
Probable duplicate of of #71. Multiple editors are unsupported and may cause AceJump to crash. Thank you for reporting.

**Closed by breandan** 2019-10-30 00:49 UTC
Labels: bug
