### ISSUE TITLE
Access is allowed from event dispatch thread only

### ISSUE THREAD

**Issue by h0tk3y** [acejump/AceJump#294] opened 2019-07-08 17:42 UTC
```
Access is allowed from event dispatch thread only.

com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: EventQueue.isDispatchThread()=false Toolkit.getEventQueue()=com.intellij.ide.IdeEventQueue@313b6132
Current thread: Thread[ApplicationImpl pooled thread 408,4,Idea Thread Group] 931018134
SystemEventQueueThread: Thread[AWT-EventQueue-0 2019.3#IU-193.1025 IDEA, eap:true, os:Windows 10 10.0, java-version:JetBrains s.r.o 11.0.3+12-b326.2 2019.3#IU-193.1025 IDEA, eap:true, os:Windows 10 10.0, java-version:JetBrains s.r.o 11.0.3+12-b326.2,6,Idea Thread Group] 2063154661
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:1067)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:1056)
	at com.intellij.openapi.editor.impl.view.EditorView.assertIsDispatchThread(EditorView.java:661)
	at com.intellij.openapi.editor.impl.view.EditorView.offsetToVisualPosition(EditorView.java:184)
	at com.intellij.openapi.editor.impl.EditorImpl.offsetToVisualPosition(EditorImpl.java:1439)
	at com.intellij.openapi.editor.impl.EditorImpl.offsetToVisualPosition(EditorImpl.java:1433)
	at org.acejump.search.AceUtilKt.getPoint(AceUtil.kt:88)
	at org.acejump.view.Marker.<init>(Marker.kt:68)
	at org.acejump.label.Tagger.markAndMapTags(Tagger.kt:158)
	at org.acejump.label.Tagger.markOrScrollToNextOccurrence(Tagger.kt:148)
	at org.acejump.label.Tagger.markOrJump(Tagger.kt:68)
	at org.acejump.search.Finder.tag(Finder.kt:134)
	at org.acejump.search.Finder.search(Finder.kt:104)
	at org.acejump.search.Finder.search$default(Finder.kt:98)
	at org.acejump.search.Finder$skimThenSearch$1.invoke(Finder.kt:86)
	at org.acejump.search.Finder$skimThenSearch$1.invoke(Finder.kt:30)
	at org.acejump.control.Trigger.invoke(Trigger.kt:29)
	at org.acejump.control.Trigger.invoke(Trigger.kt:12)
	at org.acejump.control.Trigger$invoke$$inlined$runAsync$1.run(promise.kt:189)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by breandan** [comment] 2019-07-08 18:06
Duplicate of #251, thank you for reporting.

**Closed by breandan** 2019-07-08 18:06 UTC
