### ISSUE TITLE
Cycling through tagged results on screen via "Enter" or "Shift+Enter" keys does not work any more

### ISSUE THREAD

**Issue by Skorpionos** [acejump/AceJump#380] opened 2021-07-07 18:29 UTC
**Describe the bug**
Feature "Pressing Enter or Shift+Enter during a search will cycle through tagged results on screen" doesn't work in new version AceJump

**To Reproduce**
1. Activate AceJumpMode
2. Type something that matches several times
3. Press "Enter"
4. See error "File is read-only". Action has no results

**Screenshot**
![acejump](https://user-images.githubusercontent.com/31373596/124810516-1a8e6880-df6a-11eb-80ac-9e55491fe097.png)

**Desktop (please complete the following information):**
 - Ubuntu18
 - Clion2021.1.3
 - AceJump 3.8.3

**Comment by breandan** [comment] 2021-07-07 18:33
This issue is a duplicate of #356, thank you for reporting!

**Comment by Skorpionos** [comment] 2021-07-07 19:14
By the way, I see that key "Alt+Enter" which binds in my case for action "Action: EditorStartNewLine" works instead of "Shift+Enter" for previous match. Maybe there is some workaround instead of "Enter" for next match also?...

**Comment by breandan** [comment] 2021-11-15 02:49
Okay! After some digging, I can reproduce this issue, but *only* when IdeaVim is active. If IdeaVim is disabled, tag navigation using <kbd>Enter</kbd>/<kbd>Shift</kbd>+<kbd>Enter</kbd> triggers the callback as expected, however when IdeaVim is active (either in normal mode, or insert mode), this causes the caret move in editor, or produces the message `File is read-only`. To receive callbacks for these events, we are registering an `editorActionHandler` in our `plugin.xml` file as follows:

https://github.com/acejump/AceJump/blob/6858b745e676fff4b8413395317a2943b65de3f6/src/main/resources/META-INF/plugin.xml#L26-L29

When IdeaVim is enabled, this action handler would not appear to work. I wonder if there is a better way to steal editor actions like <kbd>Enter</kbd>/<kbd>Shift</kbd>+<kbd>Enter</kbd> from the IDE when AceJump is active. I remember an older issue (#266) where competing focus occurred in certain IdeaVim modes. @AlexPl292 Should we be doing anything differently here?

**Comment by chylex** [comment] 2021-11-15 10:32
IdeaVIM registers a raw key handler that takes priority over everything else, I ran into a similar issue with one of my plugins. You could try copying my approach and see if that works:

https://github.com/chylex/IntelliJ-Keyboard-Master/commit/e0bd7778dfebde88265d4e8bd7c2fb5f2941f268

**Comment by AlexPl292** [comment] 2021-11-15 12:11
IdeaVim had a workaround for AceJump, but it was broken by the last huge refactoring. We are already discussing on how to fix it in a better way. I hope that the fix will be available in the next release.

**Comment by AlexPl292** [comment] 2021-11-16 08:41
A fix will be available with the next release of IdeaVim. It was fixed by introducing a dependency to the AceJump plugin, but actually we're discussing IdeaVim keys handling refactoring.

**Comment by breandan** [comment] 2021-11-21 07:43
Much appreciated! Please let us know when your next release is ready for testing and if we need to make any changes to support the integration. We release `3.8.5` when this issue is resolved, alongside the other [recent changes](https://github.com/acejump/AceJump/blob/master/CHANGES.md#385).

**Comment by AlexPl292** [comment] 2021-12-10 07:18
We've released a new version 1.9.0 with a workaround that should fix the issues. However, we're working on a new shortcut registering mechanism that should fix the issue properly :)

**Comment by breandan** [comment] 2021-12-11 17:16
I have confirmed that AceJump's <kbd>Enter</kbd>/<kbd>Shift</kbd>+<kbd>Enter</kbd> functionality now works again with the latest version of IdeaVim. Thanks for looking into this Alex! We will now release `3.8.5`.

**Closed by breandan** 2021-12-11 17:16 UTC
Labels: bug
