### ISSUE TITLE
Block caret forgotten when used with IdeaVim

### ISSUE THREAD

**Issue by sygutss** [acejump/AceJump#278] opened 2019-03-25 10:04 UTC
After the last update. When we use AceJump, after searching process the cursor is broken.

Description:
If we are in VIM command mode and we use ace jump then our cursor changed looks on normal mode but we will still in command mode.

Short movie attached.
[example.zip](https://github.com/acejump/AceJump/files/3002661/example.zip)

**Comment by breandan** [comment] 2019-03-25 10:19
Thank you for reporting. At the moment, AceJump does not play well together with IdeaVim at the moment (see also #68). This is due to the way that IdeaVim and AceJump intercept keystrokes. Since we currently use IDE action keymap to detect mode changes (e.g. `Enter`, the default IDE keybinding for action “new line start” will trigger selection when AceJump is enabled), this can cause some conflict with IdeaVim, which suppresses certain actions from firing when it is in Normal mode. Does this issue occur when IdeaVim is disabled?

**Comment by sygutss** [comment] 2019-03-25 10:30
Probably not because it's connected with the appearance of the caret/cursor. In command mode it should look like a small rectangle and in insertion mode, it should look like a line. The problem is connected with the fact that after usage of aceJump caret/cursor change his appearance on looks like in insertion mode but we are still in command mode and should still look like a small rectangle.

You can look at the movie in attachments.

It's strange because in previous version everything works fine with VimMode :)

**Comment by breandan** [comment] 2019-04-07 18:18
I can reproduce this issue on AceJump `3.5.5` (but not `3.5.4`). It appears to be an issue with how [`Model.naturalBlock`](https://github.com/acejump/AceJump/blob/5496ac98ca1bd3b10776e76aa5e87ed6ee59233b/src/main/kotlin/org/acejump/view/Model.kt#L37) is [saved](https://github.com/acejump/AceJump/blob/cd62211dc779c05899073357700b393c8d94bc5b/src/main/kotlin/org/acejump/control/Handler.kt#L140) and [restored](https://github.com/acejump/AceJump/blob/cd62211dc779c05899073357700b393c8d94bc5b/src/main/kotlin/org/acejump/control/Handler.kt#L156) when AceJump is [activated](https://github.com/acejump/AceJump/blob/cd62211dc779c05899073357700b393c8d94bc5b/src/main/kotlin/org/acejump/control/Handler.kt#L58) and [deactivated](https://github.com/acejump/AceJump/blob/cd62211dc779c05899073357700b393c8d94bc5b/src/main/kotlin/org/acejump/control/Handler.kt#L115-L120). No sure yet what the fix is, but it will be addressed in the next release.

**Comment by sygutss** [comment] 2019-04-07 18:50
Thanks for the answer :). Yes, like I mentioned before problem exists only on version 3.5.5. On version 3.5.4 everything works fine :). So I will be waiting for the next release :) 

Thank you for your job.
I really appreciate it.
It's the best plugin ever ;)

**Comment by breandan** [comment] 2019-05-18 05:24
Should be fixed in [AceJump `3.5.6`](https://plugins.jetbrains.com/plugin/7086-acejump/update/62467). Thanks, @AlexPl292!

**Comment by igor-akhmetov** [comment] 2023-03-30 15:45
@AlexPl292 This still seems to be an issue for me with Rider 2023.1 and latest IdeaVim/AceJump. After I open a new line with "o", I can't exit the insert mode.

**Closed** 2023-12-19 22:44 UTC
Labels: bug
