### ISSUE TITLE
Generated tags can visually overlap

### ISSUE THREAD

**Issue by saroff** [acejump/AceJump#228] opened 2018-04-03 15:38 UTC
See attached screenshot, tag containing 3 letters can't be selected, because another tag will be selected after first 2 letters are typed.

![image](https://user-images.githubusercontent.com/6500849/38259391-8cb8d790-376d-11e8-9382-66d32067aaa2.png)

**Comment by breandan** [comment] 2018-04-06 02:48
@saroff Thank you for the detailed bug reports! This is a problem I have also noticed if the tags are bunched too closely. However, this is not caused by ambiguous tags, but overlapping tags. The tag on line 1095 you highlighted is not really `IH` (although it looks like it) but `HG` `I?` and `JH` (there are three tags on line 1095). There are two problems here: first, tags can visually overlap and second, typing a key in line mode does not remove unrelated tags. The first issue is a regression in [`Marker`](https://github.com/johnlindquist/AceJump/blob/master/src/main/kotlin/com/johnlindquist/acejump/view/Marker.kt), which paints tags to the screen. And the second issue is caused by a problem in [`Finder`](https://github.com/johnlindquist/AceJump/blob/master/src/main/kotlin/com/johnlindquist/acejump/search/Finder.kt), which removes old highlights. For these reasons, Line Mode is slightly unstable in the latest release.

**Comment by breandan** [comment] 2018-10-08 23:05
I think a quick solution here could be to draw a border around the tags to visually separate adjacent but overlapping tags.

**Comment by breandan** [comment] 2021-04-04 04:10
This should be fixed in [`3.7.0`](https://plugins.jetbrains.com/plugin/7086-acejump/versions/stable/115735). Feel free to give it a try and leave you feedback!

**Closed by breandan** 2021-04-04 04:10 UTC
Labels: bug
