### ISSUE TITLE
when have "AQ" and "Q" tag,  pressed "AQ" but jump to "Q" tab

### ISSUE THREAD

**Issue by MaxSherry** [acejump/AceJump#351] opened 2021-02-05 02:35 UTC
![QQ图片20210205103455](https://user-images.githubusercontent.com/3919535/106981864-d110d600-679d-11eb-9d6e-7509a8eb252d.png)

**Comment by breandan** [comment] 2021-02-05 06:09
Looks like a duplicate of #327, thanks for reporting!

**Closed by breandan** 2021-02-05 06:09 UTC
Labels: bug
