### ISSUE TITLE
Holding down shift when typing the last tag character to select text but not include the last character

### ISSUE THREAD

**Issue by HelKim** [acejump/AceJump#337] opened 2020-09-15 02:11 UTC
**Describe the bug**

![image](https://user-images.githubusercontent.com/30397458/93156042-e6775c00-f739-11ea-8019-163981c732cd.png)

First, my cursor at line 32 'm'，I want to select all text from current to line 33 (targe)t. So, I use ctrl + ; and type 't' and hold shift when typing tag, but the selected text not include char 't'. Expected, it will include 't'.

If there isn't a bug, how can I to achieve the goal?
Thanks!

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Idea 2020.2.1
 - AceJump version: 3.6.3

**Comment by breandan** [comment] 2020-09-15 02:35
Thank you for reporting, I think this is a duplicate of #225 -- it should be configurable. Since we cannot know which location the user prefers, AceJump always jumps to the location before the search text by default. Perhaps the correct behaviour for shift selection is to always jump to the location after the search. Until this is supported, you can search for the text one character ahead of the selection end (i.e. ` ` in your screenshot).

**Closed by breandan** 2020-09-15 02:35 UTC
Labels: bug
