### ISSUE TITLE
When press Ctrl+Shift+; in Pycharm Console java.lang.IllegalArgumentException: Wrong start: -1; end=0

### ISSUE THREAD

**Issue by kraytor** [acejump/AceJump#286] opened 2019-05-15 12:59 UTC
Got this exception in Acejump(3.5.5) on Pycharm 2019.1.2

`java.lang.IllegalArgumentException: Wrong start: -1; end=0
	at com.intellij.openapi.editor.impl.RangeMarkerImpl.<init>(RangeMarkerImpl.java:71)
	at com.intellij.openapi.editor.impl.RangeMarkerImpl.<init>(RangeMarkerImpl.java:50)
	at com.intellij.openapi.editor.impl.RangeHighlighterImpl.<init>(RangeHighlighterImpl.java:68)
	at com.intellij.openapi.editor.impl.MarkupModelImpl.addRangeHighlighterAndChangeAttributes(MarkupModelImpl.java:115)
	at com.intellij.openapi.editor.impl.MarkupModelImpl.addRangeHighlighter(MarkupModelImpl.java:166)
	at org.acejump.search.Finder.createTextHighlight(Finder.kt:128)
	at org.acejump.search.Finder.access$createTextHighlight(Finder.kt:28)
	at org.acejump.search.Finder$paintTextHighlights$1.invoke(Finder.kt:116)
	at org.acejump.search.Finder$paintTextHighlights$1.invoke(Finder.kt:28)
	at org.acejump.search.AceUtilKt$sam$java_lang_Runnable$0.run(AceUtil.kt)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:435)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:419)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:403)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:729)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:678)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:373)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)`

**Comment by breandan** [comment] 2019-05-18 05:28
Duplicate of #242, should be fixed in AceJump `3.5.6`. Thank you for reporting.

**Closed by breandan** 2019-05-18 05:28 UTC
Labels: bug
