### ISSUE TITLE
Pressing Tab/Enter/→/←/↑ does not work with IdeaVim's normal mode

### ISSUE THREAD

**Issue by breandan** [acejump/AceJump#266] opened 2018-12-21 23:28 UTC
Pressing <kbd>Tab</kbd> to scroll to next screenful or <kbd>Enter</kbd> to select the nearest tag does not work with IdeaVim when in normal mode. This is due to the way we [map such actions](https://github.com/acejump/AceJump/blob/02b8902aec852ec7c84b00a37b24312137bfdf91/src/main/kotlin/org/acejump/control/Handler.kt#L33), since IdeaVim intercepts these keys and does not pass them through to the IDE, we do not receive any callback.

**Comment by breandan** [comment] 2019-05-18 17:32
@AlexPl292 Any suggestions?

**Comment by AlexPl292** [comment] 2019-07-03 11:36
Hey @breandan 
Just to clarify our plans: yesterday we've released an EAP version of IdeaVim, which is actually a release candidate, and we want to release a stable version next week (depends on EAP, but I think that'll be fine). So, now we have a kind of "feature freeze".
Meanwhile, [request](https://youtrack.jetbrains.com/issue/VIM-820) about supporting "easymotion" has become the most voted issue, so because of this (and also because I've mapped AceJump to `<leader>f` and started to use AceJump on a daily basis), we are going to implement the integration right after the release. That will take some time because for now, we don't have any commands that work in "interactive" mode yet, but I don't think it will be a big problem. A few days ago I created a small prototype and it works pretty fine.

**Comment by breandan** [comment] 2019-07-03 17:36
Hi @AlexPl292, that’s great to hear. I’ve been following your work on IdeaVim and am looking forward to better AceJump/Easymotion integration. Few free to ping me if you have any questions about our implementation here - I’ve tried to document the code as much as possible.

**Comment by AlexPl292** [comment] 2019-11-20 09:14
The issue is fixed with a new 0.54 version.

**Closed** 2020-11-30 15:21 UTC
Labels: bug
