### ISSUE TITLE
can't save settings

### ISSUE THREAD

**Issue by zlsq** [acejump/AceJump#248] opened 2018-09-12 14:10 UTC
I want to change the color of the cart,so I change the settings in settings/tools/aceJump; but when I restart IDEA, the config has reset. I have try to reinstall the plugin twice,but it doesn't work.
system: windows 10
version: idea community 2018.2.3 the newest AceJump version.

**Comment by breandan** [comment] 2018-10-08 15:07
Duplicate of #226, thank you for reporting this issue.

**Closed by breandan** 2018-10-08 15:07 UTC
